[project]
name = "crawling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "fastparquet>=2024.11.0",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "pandarallel>=1.6.5",
    "pandas>=2.3.3",
    "playwright>=1.55.0",
    "psycopg2-binary>=2.9.11",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.44",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "ruff>=0.14.0",
]
